### PR TITLE
Add react-native-svg as a dependancy.

### PR DESCRIPTION
**Pull request by nating**

### CODE REVIEW

**Comment by fabrik42** [comment]
Hey! Thank you for this lib, please keep up the good work!

This change makes sense, otherwise the lib won't work. Just ran into this issue.
Maybe it would also make sense to let the people know in the readme, that there will be manual linking involved.

**Comment by nating** [comment]
Hey, @fabrik42 - no worries.

I merged this now. What do you mean about manual linking?

**Comment by fabrik42** [comment]
Hey, very cool, thanks!

I was referring to the SVG dependency. You will have to link the native libs after installation and maybe a hint in the readme would be helpful.

Maybe the better way would be to define SVG as a peer dependency?

**Comment by nating** [comment]
Yep- good shout. I'd just been using Expo so the manual linking for react-native-svg didn't cross my mind 😝. I've thrown [a note in the README.md](https://github.com/nating/react-native-custom-qr-codes/commit/9db1963601511cd8584db43187e470cb2f8e26ba) about it. That suit?

**Comment by fabrik42** [comment]
Awesome, thank you 👍

**Pull request merged**
